name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i && pnpm playwright install --with-deps

      - name: Lint
        run: pnpm lint

      - name: Unit and integration tests
        run: pnpm test:ci

      - name: E2E testa
        run: pnpm test:e2e:ci
